### ISSUE TITLE
Behavior when token is not found

### ISSUE THREAD

**Issue by yt2b** [Trippy3/aggregate_pr#23]
When `aggregate_pullreq.py` is executed without token and `data` folder is empty, `pr.db` was created and exit with error.

```
$ python aggregate_pullreq.py <repository_url>
Warning: Token file does not exist. path: /home/user/Programs/Github/aggregate_pr/.token
"/home/user/Programs/Github/aggregate_pr/data/pr.db" does not exist. Create a new DB file and continue.
Error Status: 401
```

In the above state, `aggregate_pullreq.py` doesn't work correctly although token exists.

```
$ python aggregate_pullreq.py <repository_url>
Traceback (most recent call last):
  File "/home/user/Programs/Github/aggregate_pr/aggregate_pullreq.py", line 64, in <module>
    main()
  File "/home/user/Programs/Github/aggregate_pr/aggregate_pullreq.py", line 43, in main
    db.write_data(all_pr)
  File "/home/user/Programs/Github/aggregate_pr/modules/database.py", line 51, in write_data
    only_add = get_only_additional(ldf)
  File "/home/user/Programs/Github/aggregate_pr/modules/database.py", line 44, in get_only_additional
    original = self.to_ldf()
  File "/home/user/Programs/Github/aggregate_pr/modules/database.py", line 56, in to_ldf
    return self.conn.sql(f"{ALL_SELECT}").pl().lazy()
duckdb.CatalogException: Catalog Error: Table with name merged_pr does not exist!
Did you mean "pg_am"?
```

If I do one of the following, it works correctly.
* remove data/pr.db
* run with `--init` option

It would be better to exit immediately if token doesn't exist.

**Comment by Trippy3** [comment]
Thanks!
Permanent measures will be addressed in #24.
